apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-exporter
  name: nginx-exporter
spec:
  ports:
  - name: http
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: nginx-exporter
  type: LoadBalancer
