apiVersion: v1
kind: ConfigMap
metadata:
  name: example-vault-agent-config-nginx
  namespace: default
data:
  vault-agent-config.hcl: |
    # Comment this out if running as sidecar instead of initContainer
    exit_after_auth = true

    pid_file = "/home/vault/pidfile"

    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "otus"
            }
        }

        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    }

    template {
    destination = "/etc/secrets_html/index.html"
    contents = <<EOT
    <html>
    <body>
    <p>Some secrets:</p>
    {{- with secret "otus/otus-ro/config" }}
    <ul>
    <li><pre>username: {{ .Data.username }}</pre></li>
    <li><pre>password: {{ .Data.password }}</pre></li>
    </ul>
    {{ end }}
    </body>
    </html>
    EOT
    }

    template {
    destination = "/etc/secrets/ca.crt"
    contents = "{{ with secret \"pki_int/issue/example-dot-ru\" \"common_name=nginx.example.ru\" \"ttl=24h\" }}{{ .Data.issuing_ca }}{{ end }}"
    }
    template {
    destination = "/etc/secrets/tls.key"
    contents = "{{ with secret \"pki_int/issue/example-dot-ru\" \"common_name=nginx.example.ru\" \"ttl=24h\" }}{{ .Data.private_key }}{{ end }}"
    }
    template {
    destination = "/etc/secrets/tls.crt"
    contents = "{{ with secret \"pki_int/issue/example-dot-ru\" \"common_name=nginx.example.ru\" \"ttl=24h\" }}{{ .Data.certificate }}{{ end }}"
    }