## Using default values from https://github.com/helm/charts/blob/master/stable/grafana/values.yaml
##
grafana:
  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: true

    ## Annotations for Grafana Ingress
    ##
    annotations: {
      kubernetes.io/ingress.class: nginx
    }

    hosts:
      - grafana.35.222.119.183.xip.io
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100/
      access: proxy

prometheusOperator:
  ##
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool

  createCustomResource: false
  tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

prometheus:
  prometheusSpec:
    #nodeSelector:
    #  cloud.google.com/gke-nodepool: infra-pool
    tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
    serviceMonitorSelectorNilUsesHelmValues: false

  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx
    }

    hosts:
      - prometheus.35.222.119.183.xip.io
